apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: '{{ .Chart.name }}-appset'
  namespace: '{{ .Chart.name }}'
spec:
  generators:
    - list:
        elements:
          - app: my-chart
  template:
    metadata:
      name: 'dev-app'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default 
      sources:
      - repoURL: https://github.com/SimbaChiu/MyClusterCharts
        targetRevision: main
        path: '{{app}}'
      #   helm:
      #     valueFiles:
      #       - $values/dev/values.yaml
      # - repoURL: https://github.com/SimbaChiu/MyClusterCharts
      #   targetRevision: main
      #   ref: values
      destination:
        namespace: '{{ .Chart.name }}'
        server: https://kubernetes.default.svc
      syncPolicy: 
        automated:
          prune: true
          selfHeal: true
