apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
  template:
    metadata:
      name: '{{env}}-app'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default 
      sources:
      - repoURL: https://github.com/SimbaChiu/MyClusterGitOps
        targetRevision: main
        path: '{{env}}'
        # helm:
        #   valueFiles:
        #     - ../base/values.yaml
      destination:
        namespace: '{{env}}'
        server: https://kubernetes.default.svc
      syncPolicy: 
        automated:
          prune: true
          selfHeal: true
