apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base-appset
  # namespace: base-ns
spec:
  generators:
    - list:
        elements:
          - env: dev
  template:
    metadata:
      name: '{{env}}-app'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: '{{env}}'
        server: 'https://kubernetes.default.svc'
      project: default 
      source:
        repoURL: https://github.com/SimbaChiu/MyClusterGitOps
        path: '{{env}}'
        targetRevision: main
        helm:
          valueFiles:
            - /base/values.yaml
      syncPolicy: 
        automated:
          prune: true
          selfHeal: true
